spring:
  application:
    name: despesas
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
openai:
  api:
    key: ${CHAVE_API}
logging:
  pattern:
    console: '%clr(%d{dd-MM-yyyy HH:mm:ss}){faint} %clr(%5p) %clr([%t]){faint} %clr(%-40.40logger){cyan} %clr(:){yellow} %m%n'
server:
  port: ${PORT:8080}
