spring:
  application:
    name: despesas
  datasource:
    url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
    username: postgres.vheokzydhkcialrinfdx
    password: F1r3w@@ll
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


